[package]
name = "intellipilot-auth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
intellipilot-core = { path = "../core" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
argon2 = { workspace = true }
pasetors = { workspace = true }
rand = { workspace = true }
subtle = { workspace = true }
sha2 = { workspace = true }
zeroize = { workspace = true }
zxcvbn = { workspace = true }
webauthn-rs = { workspace = true }
totp-rs = { workspace = true }
base32 = { workspace = true }
chacha20poly1305 = { workspace = true }
hkdf = { workspace = true }
