//! OpenAPI 3.1 document.

use utoipa::OpenApi;

use crate::dto::{
    AcceptInviteRequest, AddMemberRequest, AuthConfigResponse, ChangeMemberRoleRequest,
    ChangePasswordRequest, CreateProjectRequest, CreateRoleRequest, CreateTaxonomyItemRequest,
    InviteRequest, InviteResponse, LoginRequest, MoveTaxonomyItemRequest, PasskeyAuthStartRequest,
    PasskeyFinishRequest, PasswordResetConfirmBody, PasswordResetRequestBody,
    PasswordResetRequestResponse, ProfileUpdateRequest, RecoveryCodesResponse, RegisterRequest,
    TokenResponse, TotpConfirmRequest, TotpStartResponse, TwoFactorVerifyRequest,
    UpdateProjectRequest, UpdateRoleRequest, UpdateTaxonomyItemRequest,
};
use crate::health::{LiveResponse, ReadyResponse, VersionResponse};
use crate::problem::{FieldErrorView, Problem};

#[derive(Debug, OpenApi)]
#[openapi(
    info(
        title = "IntelliPilot API",
        version = "0.5.18",
        description = "Lightweight project management API.",
        contact(
            name = "IntelliSoftAlpin eG",
            url = "https://github.com/IntelliSoftAlpin/intellipilot"
        ),
        license(name = "MIT")
    ),
    paths(
        crate::health::live,
        crate::health::ready,
        crate::health::version,
        crate::auth::handlers::config,
        crate::auth::handlers::register,
        crate::auth::handlers::login,
        crate::auth::handlers::refresh,
        crate::auth::handlers::logout,
        crate::auth::handlers::password_reset_request,
        crate::auth::handlers::password_reset_confirm,
        crate::me::get_me,
        crate::me::patch_me,
        crate::avatar::upload_avatar,
        crate::avatar::set_emoji_avatar,
        crate::avatar::delete_avatar,
        crate::avatar::serve_avatar,
        crate::me::delete_me,
        crate::me::change_password,
        crate::me::export_me,
        crate::mfa::two_factor_verify,
        crate::mfa::totp_start,
        crate::mfa::totp_confirm,
        crate::mfa::totp_disable,
        crate::mfa::recovery_regenerate,
        crate::passkeys::register_start,
        crate::passkeys::register_finish,
        crate::passkeys::list,
        crate::passkeys::delete,
        crate::passkeys::authenticate_start,
        crate::passkeys::authenticate_finish,
        crate::projects::create_project,
        crate::projects::list_projects,
        crate::projects::get_project,
        crate::projects::update_project,
        crate::projects::delete_project,
        crate::projects::accept_invitation,
        crate::admin::handlers::list_users,
        crate::admin::handlers::create_user,
        crate::admin::handlers::update_user,
        crate::admin::handlers::delete_user,
        crate::admin::handlers::reset_password,
        crate::admin::handlers::create_invitation,
        crate::admin::handlers::list_invitations,
        crate::admin::handlers::revoke_invitation,
        crate::admin::handlers::create_app_token,
        crate::admin::handlers::list_app_tokens,
        crate::admin::handlers::get_app_token,
        crate::admin::handlers::update_app_token,
        crate::admin::handlers::revoke_app_token,
        crate::admin::handlers::get_settings,
        crate::admin::handlers::update_settings,
        crate::admin::handlers::update_branding,
        crate::admin::handlers::upload_branding_icon,
        crate::admin::handlers::delete_branding_icon,
        crate::branding::get_icon,
        crate::time_tracking::list_my_assigned_issues,
        crate::time_tracking::list_my_entries,
        crate::time_tracking::log_my_time,
        crate::time_tracking::update_my_entry,
        crate::time_tracking::delete_my_entry,
        crate::time_tracking::book_absence,
        crate::time_tracking::delete_absence_booking,
        crate::time_tracking::my_timesheet_summary,
        crate::time_tracking::my_vacation_balance,
        crate::time_tracking::export_my_time,
        crate::time_tracking::list_project_time,
        crate::time_tracking::project_team_month,
        crate::time_tracking::admin_log_time,
        crate::time_tracking::admin_update_entry,
        crate::time_tracking::admin_delete_entry,
        crate::time_tracking::list_locks,
        crate::time_tracking::lock_period,
        crate::time_tracking::unlock_period,
        crate::time_tracking::project_availability,
        crate::time_tracking::issue_time,
        crate::time_tracking::export_project_time,
        crate::time_tracking::list_user_allowances,
        crate::time_tracking::set_user_allowance,
        crate::time_tracking::set_user_work_settings,
        crate::issues_io::export_issues,
        crate::issues_io::import_preview,
        crate::issues_io::import_commit,
        crate::dashboard::get_home,
        crate::dashboard::get_project,
    ),
    components(schemas(
        LiveResponse,
        ReadyResponse,
        VersionResponse,
        Problem,
        FieldErrorView,
        RegisterRequest,
        LoginRequest,
        TokenResponse,
        ProfileUpdateRequest,
        ChangePasswordRequest,
        AuthConfigResponse,
        PasswordResetRequestBody,
        PasswordResetRequestResponse,
        PasswordResetConfirmBody,
        TotpStartResponse,
        TotpConfirmRequest,
        RecoveryCodesResponse,
        TwoFactorVerifyRequest,
        PasskeyFinishRequest,
        PasskeyAuthStartRequest,
        CreateProjectRequest,
        UpdateProjectRequest,
        CreateRoleRequest,
        UpdateRoleRequest,
        InviteRequest,
        InviteResponse,
        AcceptInviteRequest,
        ChangeMemberRoleRequest,
        AddMemberRequest,
        intellipilot_core::user::User,
        intellipilot_core::user::UserBrief,
        intellipilot_core::user::ProfileCard,
        intellipilot_core::user::OutToday,
        crate::avatar::SetEmojiAvatarRequest,
        intellipilot_core::project::Project,
        intellipilot_core::project::EpicBoardSettings,
        intellipilot_core::project::Role,
        intellipilot_core::project::Membership,
        intellipilot_core::project::Invitation,
        intellipilot_core::project::Visibility,
        intellipilot_core::perms::Permission,
        CreateTaxonomyItemRequest,
        UpdateTaxonomyItemRequest,
        MoveTaxonomyItemRequest,
        intellipilot_core::taxonomy::TaxonomyItem,
        intellipilot_core::taxonomy::TaxonomyKind,
        crate::dto::CreateEpicRequest,
        crate::dto::UpdateEpicRequest,
        crate::dto::CreateIssueRequest,
        crate::dto::UpdateIssueRequest,
        crate::dto::BulkCreateIssuesRequest,
        crate::dto::ReorderRequest,
        crate::dto::CommentRequest,
        intellipilot_core::backlog::Epic,
        intellipilot_core::backlog::Issue,
        intellipilot_core::backlog::Comment,
        intellipilot_core::backlog::EntityKind,
        crate::dto::CreateLabelRequest,
        crate::dto::UpdateLabelRequest,
        crate::dto::CreateComponentRequest,
        crate::dto::UpdateComponentRequest,
        intellipilot_core::catalog::Label,
        intellipilot_core::catalog::Component,
        crate::repositories::CreateSshKeyRequest,
        crate::repositories::UpdateSshKeyRequest,
        crate::repositories::CreateRepositoryRequest,
        crate::repositories::UpdateRepositoryRequest,
        crate::repositories::PreviewBranchesRequest,
        crate::repositories::LinkRepositoryRequest,
        crate::repositories::UpdateLinkRequest,
        intellipilot_core::repo::SshKey,
        intellipilot_core::repo::Repository,
        intellipilot_core::repo::ComponentRepositoryLink,
        intellipilot_core::repo::RemoteBranches,
        crate::customers::CreateCustomerRequest,
        crate::customers::UpdateCustomerRequest,
        crate::releases::CreateReleaseRequest,
        crate::releases::UpdateReleaseRequest,
        crate::releases::CreateVersionRequest,
        crate::releases::UpdateVersionRequest,
        crate::releases::ForComponentsRequest,
        crate::releases::LinkReleaseRequest,
        crate::issue_relations::CreateLinkRequest,
        crate::issue_relations::AddWatcherRequest,
        intellipilot_core::customer::Customer,
        intellipilot_core::board::Board,
        intellipilot_core::board::BoardVisibility,
        intellipilot_core::board::BoardColumn,
        intellipilot_core::board::BoardLane,
        crate::boards::CreateBoardRequest,
        crate::boards::UpdateBoardRequest,
        intellipilot_core::release::Release,
        intellipilot_core::release::ReleaseVersion,
        intellipilot_core::release::ReleaseStatus,
        intellipilot_core::release::ComponentReleaseLink,
        intellipilot_core::backlog::IssueCategory,
        intellipilot_core::backlog::Resolution,
        intellipilot_core::backlog::LinkType,
        intellipilot_core::backlog::IssueLink,
        crate::dto::CreateMilestoneRequest,
        crate::dto::UpdateMilestoneRequest,
        crate::dto::SetMilestoneEpicsRequest,
        intellipilot_core::milestone::Milestone,
        intellipilot_core::milestone::MilestoneStats,
        intellipilot_core::attachment::Attachment,
        crate::dto::CreateWikiPageRequest,
        crate::dto::UpdateWikiPageRequest,
        intellipilot_core::wiki::WikiPage,
        intellipilot_core::wiki::WikiRevision,
        intellipilot_core::search::SearchHit,
        crate::admin::dto::UserListResponse,
        crate::admin::dto::ActivityListResponse,
        intellipilot_core::activity::ActivityEvent,
        crate::admin::dto::CreateUserRequest,
        crate::admin::dto::CreateUserResponse,
        crate::admin::dto::UpdateUserRequest,
        crate::admin::dto::PasswordResetIssuedResponse,
        crate::admin::dto::CreateInvitationRequest,
        crate::admin::dto::CreateInvitationResponse,
        crate::admin::dto::PendingInvitation,
        crate::admin::dto::CreateAppTokenRequest,
        crate::admin::dto::CreateAppTokenResponse,
        crate::admin::dto::UpdateAppTokenRequest,
        intellipilot_core::app_token::AppToken,
        crate::admin::dto::PlatformSettingsResponse,
        crate::admin::dto::UpdateSettingsRequest,
        crate::admin::dto::UpdateBrandingRequest,
        crate::admin::dto::NotificationSettingsResponse,
        crate::admin::dto::UpdateNotificationSettingsRequest,
        crate::admin::dto::TestMailRequest,
        crate::admin::dto::NotificationTestResponse,
        crate::time_tracking::LogTimeRequest,
        crate::time_tracking::UpdateTimeRequest,
        crate::time_tracking::BookAbsenceRequest,
        crate::time_tracking::AdminLogTimeRequest,
        crate::time_tracking::LockPeriodRequest,
        crate::time_tracking::SetAllowanceRequest,
        crate::time_tracking::SetWorkSettingsRequest,
        intellipilot_core::time_tracking::TimeEntry,
        intellipilot_core::time_tracking::TimeEntryDetail,
        intellipilot_core::time_tracking::EntryKind,
        intellipilot_core::time_tracking::PeriodLock,
        intellipilot_core::time_tracking::VacationAllowance,
        intellipilot_core::time_tracking::VacationBalance,
        intellipilot_core::time_tracking::VacationYear,
        intellipilot_core::time_tracking::TimesheetSummary,
        intellipilot_core::time_tracking::TeamMemberMonth,
        intellipilot_core::time_tracking::DayMinutes,
        intellipilot_core::time_tracking::Availability,
        crate::issues_io::ImportPreview,
        crate::issues_io::ValueMatch,
        crate::issues_io::ValueChoice,
        crate::issues_io::ImportMapping,
        crate::issues_io::ImportResult,
        intellipilot_core::time_tracking::AssignedTask,
        intellipilot_core::dashboard::HomeDashboard,
        intellipilot_core::dashboard::ProjectDashboard,
        intellipilot_core::dashboard::StatusBucket,
        intellipilot_core::dashboard::NamedCount,
        intellipilot_core::dashboard::ProjectBucket,
        intellipilot_core::dashboard::AttentionItem,
        intellipilot_core::dashboard::EpicReadiness,
        intellipilot_core::dashboard::WeekCount,
    ))
)]
pub struct ApiDoc;

/// Builds the OpenAPI document and pins the spec version to 3.1.0 explicitly.
pub fn document() -> utoipa::openapi::OpenApi {
    let mut doc = ApiDoc::openapi();
    doc.openapi = utoipa::openapi::OpenApiVersion::Version31;
    doc
}
